# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NUquHXsmypvhGQif_Zxv0BDKBL8XUawR

Here we are going to make a news article summerizer which will generate the key outputs of the link which we will give us the main contets like author name, publication date , summary as well as sentiment analysis.
"""

# importing libraries

!pip install newspaper3|k

# For natural language processing
import nltk
from textblob import TextBlob #for sentiment analysis
from newspaper import Article

url = 'https://apnews.com/article/lakers-grizzlies-lebron-morant-6a7f552a9c15c21554f6d8d288e020ed'
#you can put url of any article

article = Article(url)

article.download()

article.parse()

!pip install NLP-python

from NLP import NLP
nlp = NLP()

article.nlp

print(f'Title:{article.title}')
print(f'Authors:{article.authors}')
print(f'Publishing Date:{article.publish_date}')
print(f'Summary:{article.summary}')
#library does all the jobs we need not code for each and every thing

nltk.download('punkt')#for sentiment analysis

#sentiment analysis
#taking the whole article for analysis
analysis = TextBlob(article.text)
print(analysis.polarity)

print(f'Sentiment: {"Positive" if analysis.polarity > 0 else "Negative" if analysis.polarity < 0 else "neutral"}')